apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: beanie-kiosk-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: {{ .Values.name }}
    servicePort: 3000
  rules:
  - http:
      paths:
      - path: /test
        backend:
          serviceName: {{ .Values.name }}
          servicePort: 3000
