apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    {{- include "app.labels" . | nindent 4 }}
